fix to install node-gyp globally

diff --git a/node-install b/node-install
--- a/node-install
+++ b/node-install
@@ -37,5 +37,12 @@ else
 fi
 mv $ARCHIVE_DIRNAME $LOCATION
 
+$LOCATION/bin/npm install -g node-gyp > /tmp/node-install-npm.log 2>&1
+RETVAL=$?
+if [ $RETVAL != 0 ]; then
+    echo "npm install failed. see log /tmp/ruby-install-bundler.log"
+    exit 2
+fi
+
 echo "node $TARGET_VERSION successfully installed on $LOCATION"
 echo "To use this node, do 'export PATH=$LOCATION/bin:\$PATH'."
