fix issue #11

diff --git a/php-install b/php-install
--- a/php-install
+++ b/php-install
@@ -31,7 +31,11 @@ if [ ! -d ./var/php-build ]; then
         git clone -q git://github.com/CHH/php-build.git php-build-repo
         cd php-build-repo
         PREFIX="$XBUILD_PATH"/var/php-build ./install.sh >/dev/null 2>&1
-    ) || (echo "failed to download php-build" && exit 1)
+    )
+    if [ $? -ne 0 ]; then
+        echo "failed to download php-build"
+        exit 1
+    fi
 fi
 
 if [ "x"$FLAG_FORCE = "x" -a -d "$LOCATION" -a -x "$LOCATION/bin/php" ]; then
diff --git a/ruby-install b/ruby-install
--- a/ruby-install
+++ b/ruby-install
@@ -29,12 +29,16 @@ if [ ! -f ./var/ruby-build.date -o "x"$oldcheck = "x" ]; then
         echo "cloning latest ruby-build."
         set -e
         cd var
-        [ -d ./ruby-build ] && rm -rf ruby-build-repo ruby-build ruby-build.date
+        [ -d ./ruby-build -o -d ruby-build-repo ] && rm -rf ruby-build-repo ruby-build ruby-build.date
         git clone -q git://github.com/sstephenson/ruby-build.git ruby-build-repo
         touch ruby-build.date
         cd ruby-build-repo
         PREFIX="$XBUILD_PATH"/var/ruby-build ./install.sh >/dev/null 2>&1
-    ) || (echo "failed to download ruby-build" && exit 1)
+    )
+    if [ $? -ne 0 ]; then
+        echo "failed to download ruby-build"
+        exit 1
+    fi
 fi
 rm -f ./var/.24hours
 
@@ -69,8 +73,13 @@ fi
     if [ ! -x "$LOCATION"/bin/bundle ]; then
         gems="bundler $gems"
     fi
+    set -e
     "$LOCATION"/bin/gem install --no-rdoc --no-ri $gems > /tmp/$USER-ruby-install-bundler.log 2>&1
-) || (echo "gem install failed. see log /tmp/$USER-ruby-install-bundler.log" && exit 2)
+)
+if [ $? -ne 0 ]; then
+    echo "gem install failed. see log /tmp/$USER-ruby-install-bundler.log"
+    exit 2
+fi
 
 echo "ruby $TARGET_VERSION successfully installed on $LOCATION"
 echo "To use this ruby, do 'export PATH=$LOCATION/bin:\$PATH'."
