fix to export PATH for gem command internal path

diff --git a/ruby-install b/ruby-install
--- a/ruby-install
+++ b/ruby-install
@@ -31,12 +31,10 @@ if [ $RETVAL != 0 ]; then
     exit 1
 fi
 
-$LOCATION/bin/gem install --no-rdoc --no-ri bundler pry > /tmp/$USER-ruby-install-bundler.log 2>&1
-RETVAL=$?
-if [ $RETVAL != 0 ]; then
-    echo "gem install failed. see log /tmp/$USER-ruby-install-bundler.log"
-    exit 2
-fi
+(
+    export PATH=$LOCATION/bin:$PATH
+    $LOCATION/bin/gem install --no-rdoc --no-ri bundler pry > /tmp/$USER-ruby-install-bundler.log 2>&1
+) || (echo "gem install failed. see log /tmp/$USER-ruby-install-bundler.log" && exit 2)
 
 echo "ruby $TARGET_VERSION successfully installed on $LOCATION"
 echo "To use this ruby, do 'export PATH=$LOCATION/bin:\$PATH'."
